---
title: "Kaggle"
output: html_document
---

```{r setup, include=FALSE}
install.packages("dplyr")
library(dplyr)
setwd("~/Documents/apan5200/rentlala2021/")
train <- read.csv("analysisData.csv",stringsAsFactors = TRUE)
test <- read.csv("scoringData.csv",stringsAsFactors = TRUE)
test[is.na(test)] = 0


str(train)

model1<-lm(price~bathrooms+bedrooms+beds+room_type,data = train)
summary(model1)
pred<-predict(model1,newdata = test)
submissionFile = data.frame(id = test$id, price = pred)
write.csv(submissionFile, 'submission1.csv',row.names = F)

train %>%
  group_by(neighbourhood) %>%
  summarize(n=n())

model2<-lm(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood,data=train)
summary(model2)

test2 <- test%>%
 mutate(neighbourhood = replace(neighbourhood,neighbourhood %in% c("Bull's Head","Castleton Corners","Meiers Corners"),"Staten Island"))


  pred2<-predict(model2,newdata = test2)
submissionFile2 = data.frame(id = test$id, price = pred2)
write.csv(submissionFile2, 'submission2.csv',row.names = F)

model3<-lm(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy,data=train)
summary(model3)
pred3<-predict(model3,newdata = test3)
submissionFile3 = data.frame(id = test$id, price = pred3)
write.csv(submissionFile3, 'submission3.csv',row.names = F)
hist(residuals(model3))

test3 <- test2%>%
  mutate(property_type = replace(property_type,property_type %in% c("Lighthouse","Timeshare"),"Condominium"))%>%
  mutate(instant_bookable = ifelse(instant_bookable =="t",1,0))%>%
  mutate(has_availability = ifelse(has_availability =="t",1,0))



model4<-lm(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+minimum_nights_avg_ntm+maximum_nights_avg_ntm+availability_365,data=train)

pred4<-predict(model4,newdata = test3)
submissionFile4 = data.frame(id = test$id, price = pred4)
write.csv(submissionFile4, 'submission4.csv',row.names = F)



```

```{r}
install.packages("rpart")
install.packages("rpart.plot")
library(rpart)
library(rpart.plot)
plot(density(train$price))

tree1 = rpart(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+minimum_nights_avg_ntm+maximum_nights_avg_ntm+availability_365,data=train, method = "anova",control = rpart.control(cp=0.001))
summary(tree1)
rpart.plot(tree1)
pred5 = predict(tree1, newdata = test3, type = 'vector')
submissionFile5 = data.frame(id = test$id, price = pred5)
write.csv(submissionFile5, 'submission5.csv',row.names = F)

install.packages("caret")
library(caret)

trControl = trainControl(method='cv',number = 5)
tuneGrid = expand.grid(.cp = seq(from = 0,to = 0.1,by = 0.0001))
set.seed(617)
cvModel = train(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                data=train,
                na.action=na.exclude,
                method="rpart",
                trControl = trControl,
                tuneGrid = tuneGrid)

cvModel$results

cvModel$bestTune$cp
tree2 = rpart(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,data=train,cp = cvModel$bestTune$cp)

pred6 = predict(tree2,newdata=test3)
submissionFile6 = data.frame(id = test$id, price = pred6)
write.csv(submissionFile6, 'submission6.csv',row.names = F)


train1 <-train%>%
  mutate(instant_bookable = ifelse(instant_bookable =="t",1,0))%>%
  mutate(has_availability = ifelse(has_availability =="t",1,0))%>%
   mutate(host_is_superhost = ifelse(host_is_superhost =="t",1,0))
  



tree3 = rpart(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews+instant_bookable+has_availability,
              data=train1,cp = 0.002)


pred7 = predict(tree4,newdata=test3)
submissionFile7 = data.frame(id = test$id, price = pred7)
write.csv(submissionFile7, 'submission7.csv',row.names = F)

tree4 = rpart(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+neighbourhood+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,data=train,control = rpart.control(minbucket = 5,cp=0.003))



```


```{r}
install.packages("randomForest")
library(randomForest)
forest = randomForest(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,train, na.action =na.exclude,
                      ntree = 1000)



trControl=trainControl(method="cv",number=5)
tuneGrid = expand.grid(mtry=1:19, 
                       splitrule = c('variance','extratrees','maxstat'), 
                       min.node.size = c(2,5,10,15,20,25))
set.seed(1031)
cvModel = train(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                data=train,
                na.action =na.exclude,
                method="ranger",
                num.trees=4,
                trControl=trControl,
                tuneGrid=tuneGrid)
cvModel$bestTune


install.packages("ranger")
library(ranger)
train[is.na(train)] = 0
set.seed(1031)
cv_forest_ranger = ranger(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                          data=train,
                          num.trees = 4, 
                          mtry=cvModel$bestTune$mtry, 
                          min.node.size = cvModel$bestTune$min.node.size, 
                          splitrule = cvModel$bestTune$splitrule)

pred_train = predict(cv_forest_ranger, data = train, num.trees = 4)

pred9 = predict(cv_forest_ranger, data = test3, num.trees = 4)

pred9$predictions
submissionFile9 = data.frame(id = test$id, price = pred9$predictions)
write.csv(submissionFile9, 'submission9.csv',row.names = F)


set.seed(1031)
cvModel = train(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                data=train,
                na.action =na.exclude,
                method="ranger",
                num.trees=100,
                trControl=trControl,
                tuneGrid=tuneGrid)
cvModel$bestTune


cv_forest_ranger = ranger(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                          data=train,
                          num.trees = 100, 
                          mtry=cvModel$bestTune$mtry, 
                          min.node.size = cvModel$bestTune$min.node.size, 
                          splitrule = cvModel$bestTune$splitrule)

pred10 = predict(cv_forest_ranger, data = test3, num.trees = 100)

pred10$predictions


set.seed(1031)
cvModel500 = train(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                data=train,
                na.action =na.exclude,
                method="ranger",
                num.trees=500,
                trControl=trControl,
                tuneGrid=tuneGrid)
cvModel500$bestTune

set.seed(1031)
cv_forest_ranger2 = ranger(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews,
                          data=train,
                          num.trees = 500, 
                          mtry=cvModel500$bestTune$mtry, 
                          min.node.size = cvModel500$bestTune$min.node.size, 
                          splitrule = cvModel500$bestTune$splitrule)
pred11 = predict(cv_forest_ranger2, data = test3, num.trees = 500)

pred11$predictions
submissionFile11 = data.frame(id = test$id, price = pred11$predictions)
write.csv(submissionFile11, 'submission11.csv',row.names = F)

table(train$neighbourhood)

set.seed(1031)
cvModel12 = train(price~accommodates + neighbourhood + cleaning_fee + property_type + 
    room_type + bedrooms + neighbourhood_group_cleansed + bathrooms + 
    review_scores_rating + availability_365 + minimum_nights_avg_ntm + 
    number_of_reviews + guests_included + beds + cancellation_policy + 
    host_is_superhost + maximum_nights_avg_ntm + extra_people + 
    host_listings_count,
    data=train,
                na.action =na.exclude,
                method="ranger",
                num.trees=1000,
                trControl=trControl,
                tuneGrid=tuneGrid)
cvModel12$bestTune

set.seed(1031)
cv_forest_ranger3 = ranger(price~accommodates + neighbourhood + cleaning_fee + property_type + 
    room_type + bedrooms + neighbourhood_group_cleansed + bathrooms + 
    review_scores_rating + availability_365 + minimum_nights_avg_ntm + 
    number_of_reviews + guests_included + beds + cancellation_policy + 
    host_is_superhost + maximum_nights_avg_ntm + extra_people + 
    host_listings_count,
                          data=train,
                          num.trees = 1000, 
                          mtry=cvModel12$bestTune$mtry, 
                          min.node.size = cvModel12$bestTune$min.node.size, 
                          splitrule = cvModel12$bestTune$splitrule)
pred12 = predict(cv_forest_ranger3, data = test3, num.trees = 1000)
pred12$predictions
submissionFile12 = data.frame(id = test$id, price = pred12$predictions)
write.csv(submissionFile12, 'submission12.csv',row.names = F)


```
```{r}
start_mod = lm(price~1,data=train1)
empty_mod = lm(price~1,data=train1)
full_mod = lm(price~bathrooms+bedrooms+beds+room_type+review_scores_rating+property_type+accommodates+cancellation_policy+availability_365+minimum_nights_avg_ntm+maximum_nights_avg_ntm+guests_included+extra_people+number_of_reviews+host_location+host_is_superhost+host_neighbourhood+host_listings_count+host_total_listings_count+neighbourhood_group_cleansed+smart_location+security_deposit+cleaning_fee+has_availability,data=train1)
forwardStepwise = step(start_mod,
                       scope=list(upper=full_mod,lower=empty_mod),
                       direction='forward')

```

```{r}
install.packages("xgboost")
install.packages("forcats")
library(forcats)
library(xgboost)
train2 <- train1%>%
  select(c(accommodates, cleaning_fee, 
  bedrooms,  bathrooms, review_scores_rating, availability_365, minimum_nights_avg_ntm, 
    number_of_reviews, guests_included, beds, host_is_superhost, maximum_nights_avg_ntm, extra_people, 
    host_listings_count))

neighbourhood <- model.matrix(~neighbourhood-1,train3)
neighbourhood_cleansed <- model.matrix(~neighbourhood_group_cleansed-1,train3)
property_type <- model.matrix(~property_type-1,train3)
cancellation_policy <- model.matrix(~cancellation_policy-1,train3)
room_type<-model.matrix(~room_type-1,train3)

train_numeric<-cbind(train2,neighbourhood,neighbourhood_cleansed,property_type,cancellation_policy,room_type)
train_matrix <-data.matrix(train_numeric)


train1%>%
  mutate(neighbourhood = fct_lump(f = neighbourhood,prop = 0.0058))%>%
  group_by(neighbourhood)%>%
  summarise(n=n())
  
  test3%>%
    mutate(neighbourhood = fct_lump(f = neighbourhood,prop = 0.004))%>%
  group_by(neighbourhood)%>%
  summarise(n=n())

train3<-train1%>%
  mutate(neighbourhood = fct_lump(f = neighbourhood,prop = 0.0068))%>%
  mutate(property_type = fct_lump(f = property_type,prop = 0.005))

test4<-test3%>%
mutate(neighbourhood = fct_lump(f = neighbourhood,prop = 0.0065))%>%
  mutate(property_type = fct_lump(f = property_type,prop = 0.006))
  






test5 <- test4%>%
   select(c(accommodates, cleaning_fee, 
  bedrooms,  bathrooms, review_scores_rating, availability_365, minimum_nights_avg_ntm, 
    number_of_reviews, guests_included, beds, host_is_superhost, maximum_nights_avg_ntm, extra_people, 
    host_listings_count))

neighbourhoodT <- model.matrix(~neighbourhood-1,test4)
neighbourhood_cleansedT <- model.matrix(~neighbourhood_group_cleansed-1,test4)
property_typeT <- model.matrix(~property_type-1,test4)
cancellation_policyT <- model.matrix(~cancellation_policy-1,test4)
room_typeT<-model.matrix(~room_type-1,test4)

test_numeric <-cbind(test5,neighbourhoodT,neighbourhood_cleansedT,property_typeT,cancellation_policyT,room_typeT)
test_matrix <- data.matrix(test_numeric)

train_label<-train1%>%
  select(price)


dtrain <- xgb.DMatrix(data = train_matrix, label= train_label$price)

modelx <- xgboost(data = dtrain, 
                 nrounds=10000,
                  verbose = 0,
                  early_stopping_rounds = 100)

pred13<-predict(modelx, newdata = test_matrix)




submissionFile13 = data.frame(id = test$id, price = pred13)
write.csv(submissionFile13, 'submission13.csv',row.names = F)

```

